# Java CI with Gradle and GPT Review (Fixed - All Issues Resolved)
name: Java CI with Gradle and GPT Review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# ✅ GITHUB_TOKEN과 OPENAI_API_KEY를 위한 권한 명시
permissions:
  contents: read
  pull-requests: write
  id-token: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Git 참조 문제 방지

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build

  code-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ✅ GPT 코드 리뷰 단계 - GITHUB_TOKEN과 OPENAI_API_KEY 참조 방식 수정
      - name: Code Review with GPT
        uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
